version: '3'

services:
  postgres:
    container_name: crafters_compass_postgres
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
volumes:
  postgres-data:
